version: '3.8'

# Sandbox environment for testing
services:
  wmb-chain1:
    container_name: wmb-chain1
    build: 
      context: .
    ports:
      - "18545:18545"
    command: ["yarn", "hardhat", "node", "--config", "./hardhat.chain1.config.js", "--port", "18545"]

  wmb-chain2:
    container_name: wmb-chain2
    build: 
      context: .
    ports:
      - "28545:28545"
    command: ["yarn", "hardhat", "node", "--config", "./hardhat.chain2.config.js", "--port", "28545"]

  wmb-agent:
    container_name: wmb-agent
    build: 
      context: .
    command: ["node", "./sandbox/agent.js"]

